drop table if exists cargos CASCADE;
drop table if exists funcionarios CASCADE;
drop table if exists funcionarios_unidades CASCADE;
drop table if exists unidade_trabalho CASCADE;

create table cargos
(
    id        integer generated by default as identity,
    descricao varchar(255),
    primary key (id)
);
create table funcionarios
(
    id               integer generated by default as identity,
    cpf              varchar(255),
    data_contratacao date,
    nome             varchar(255),
    salario          double,
    cargo_id         integer not null,
    primary key (id)
);
create table funcionarios_unidades
(
    fk_funcionario integer not null,
    fk_unidade     integer not null
);
create table unidade_trabalho
(
    id        integer generated by default as identity,
    descricao varchar(255),
    endereco  varchar(255),
    primary key (id)
);

alter table funcionarios
    add constraint FK94l75p7ixitcgh6l240unj9bm foreign key (cargo_id) references cargos;
alter table funcionarios_unidades
    add constraint FKgn3jpmj1h0hdy8io3beyrc13i foreign key (fk_unidade) references unidade_trabalho;
alter table funcionarios_unidades
    add constraint FKg6nq7h4hjl3njvdd4304jp2m0 foreign key (fk_funcionario) references funcionarios;